- job_id: SAS40406
  job_title: Software Developer (Emerging Career)
  company_name: SAS
  status: processed
  posting_link: https://careers-sas.icims.com/jobs/40406/software-developer-(emerging-career)-java---spring-boot/job?hub=9&mobile=false&width=1200&height=500&bga=true&needsRedirect=false&jan1offset=-300&jun1offset=-240
  job_description: ' Software Developer - (Emerging Career) Hybrid, Cary, North Carolina



    We’re a leader in data and AI. Through our software and services, we inspire customers
    around the world to transform data into intelligence - and questions into answers.



    If you''re looking for a dynamic, fulfilling career with flexibility and a world-class
    employee experience, you''ll find it here. We''re recognized around the world
    for our inclusive, meaningful culture and innovative technologies by organizations
    like Fast Company, Forbes, Newsweek and more.



    About the job

    As a Software Developer in the SAS Platform Services Division R&D organization,
    you will join a team of talented engineers working collaboratively to ideate and
    deliver leading edge, innovative products and solutions that enable SAS customers
    to deploy analytics with business rules in new ways. You will contribute to projects
    spanning a diverse set of technologies and industries.



    Are you passionate about software development and are looking for a position that
    will allow you to contribute on all levels of the software development stack?
    We are looking for developers who want to get involved with the next generation
    of SAS platform mid-tier services which act as the building blocks for the SAS
    Viya Solutions suites. In this role, you will have the opportunity to contribute
    new feature development along updates to strengthen our security policy and improve
    the performance of our platform. You will also have the opportunity to grow your
    technical skills with contributions to Java based microservices along with learning
    and/or deepening your knowledge of containerization and Azure cloud technologies.
    In this position you will not be limited because at SAS, your curiosity matters
    – whether you’re developing algorithms, creating customer experiences, or answering
    critical questions. Curiosity is our code, and the opportunities here are endless



    As a Software Developer (Emerging Career), you will:

    Be encouraged to participate in open-source projects on behalf of SAS. Design
    and develop high quality, testable and scalable software solutions in the connectivity
    space, within established timelines while adhering to R&D best practices and processes.
    Actively involve other project stakeholders (e.g. managers, developers, user interface
    and visual designers, product managers) to ensure implementation satisfies functional
    requirements and is consistent with established R&D standards. Participate in
    project scoping and scheduling; tracks progress of individual tasks and alerts
    stakeholders of issues blocking or preventing completion of task. Ensure quality
    through functional, unit and performance testing Work closely with testing by
    providing thorough reviews of the test plan and communicate when updates to the
    plan should be made to cover code changes related to enhancements, redesigns and/or
    bug fixes. Maintain accountability for the entire life cycle of the code including
    support for both internal and external consumers. Embrace curiosity, passion,
    authenticity and accountability. These are our values and influence everything
    we do. Required qualifications



    Bachelor’s degree in Computer Science or a related quantitative field 2-5 years
    of demonstratable Java programming experience as a software developer Experience
    with CI/CD tools such as Git/Gerrit/Jenkins, Github, Gitlab, or similar Experience
    with Linux Experience with Agile SDLC practices Excellent interpersonal communication
    skills Equivalent combination of related education, training and experience may
    be considered in place of the above qualifications.


    Additional competencies, knowledge and skills

    Adaptability: Maintaining effectiveness when experiencing major changes in work
    responsibilities or environment (e.g., people, processes, structure, or culture);
    adjusting effectively to change by exploring the benefits, trying new approaches,
    and collaborating with others to make the change successful. Collaborating: Working
    cooperatively with others to help a team or work group achieve its goals. Communication:
    Conveying information and ideas clearly and concisely to individuals or groups
    in an engaging manner that helps them understand and retain the message; listening
    actively to others. Experience with Spring Boot

    Experience with REST APIs design and implementation

    Experience building and orchestrating containers using technologies such as Docker
    and Kubernetes

    Experience with cloud architecture and at least one major public cloud provider

    Experience using IDE’s such as IntelliJ or VSCode

    Experience with collaboration tools such as Jira and Confluence

    Exceptional aptitude for problem solving and debugging of complex multitiered
    software applications

    World-class benefits

    Highlights include...

    Comprehensive medical, prescription, dental and vision plans. Medical plan options
    include: PPO with low annual deductible and copays. HDHP combined with a health
    savings account with a contribution from SAS (no access to on-site health care
    center). Onsite Health Care Center (HQ) that’s free to employees and family members
    enrolled in the PPO plan. There''s a pharmacy too! Not local to HQ? The pharmacy
    will ship prescriptions for no additional charge! An industry-leading 401k plan.
    Tuition Assistance Program and programs and resources to support your development
    Generous time away including vacation time, a variety of paid holidays, and our
    much-loved U.S. Winter Wellness Break between December 25 and January 1. Volunteer
    Time Off, parental leave and unlimited paid sick days. Generous childcare benefits
    for all full-time employees. You are welcome here.

    At SAS, it’s not about fitting into our culture – it’s about adding to it. We
    believe our people make the difference. Our inclusive workforce brings together
    unique talents and inspires teams to create amazing software that reflects the
    diversity of our users and customers.



    Additional Information:

    To qualify, applicants must be legally authorized to work in the United States,
    and should not require, now or in the future, sponsorship for employment visa
    status. SAS is an equal opportunity employer. All qualified applicants are considered
    for employment without regard to any characteristic protected by law. Read more:
    Know Your Rights.



    Resumes may be considered in the order they are received. SAS employees performing
    certain job functions may require access to technology or software subject to
    export or import regulations. To comply with these regulations, SAS may obtain
    nationality or citizenship information from applicants for employment. SAS collects
    this information solely for trade law compliance purposes and does not use it
    to discriminate unfairly in the hiring process.



    SAS only sends emails from verified “sas.com” email addresses and never asks for
    sensitive, personal information or money. If you have any doubts about the authenticity
    of any type of communication from, or on behalf of SAS, please contact Recruitingsupport@sas.com.



    Let''s stay in touch! Join our Talent Community to stay up to date on company
    news, job updates and more. '
- job_id: SPEC87255637744
  job_title: Software Engineer I
  company_name: Spectrum
  status: pending
  posting_link: https://jobs.spectrum.com/job/-/-/4673/87255637744?utm_source=linkedIn&utm_medium=job-listings&utm_campaign=brand&utm_term=RD-TA
  job_description: ' This role requires the ability to work lawfully in the U.S. without
    employment-based immigration sponsorship, now or in the future.

    This position is not eligible for immigration sponsorship.

    Are you ready to collaborate with technical teams to create software solutions
    that leverage prevailing technologies and enhance the Spectrum customer experience?
    As a Software Engineer I on the Enterprise Data Services team, you’ll play a key
    role in developing and supporting applications that power platforms. This position
    is ideal for someone looking to grow their skills in Java, Spring Boot, and PL/SQL
    development while gaining exposure to advanced technologies such as Elasticsearch,
    Kubernetes, Cloud, Redis, and microservices. You will learn from experienced engineers
    in a collaborative, hands-on environment.


    How You’ll Make an Impact

    Understand and code basic features, functions and definitions Write clean, maintainable,
    and efficient code following established coding standards under the supervision
    of senior developers Implement pre-designed solutions per team lead instructions,
    best practices and approved code patterns Implement basic functionality from a
    provided design with team guidance Understand technical requirements and technical
    design documents Utilize code branching strategies and change control methodologies
    Code as per the Spectrum standards and guidelines; assist in fixes to defects
    raised Complete assigned tasks within a given timeframe Test and validate code;
    submit code for code review and apply feedback Provide LOE on a capability level
    Collaborate with other teams, within a feature team, and/or a focus group Adhere
    to Spectrum’s legal, regulatory, process, and security requirements

    What You’ll Bring to Spectrum


    Required Qualifications


    Education

    BA/BS in Information Technology, Computer Science, or equivalent combination of
    education and experience Experience

    1+ years of coding, testing and designing software experience 1+ years of software
    development methodologies experience 1+ years of database management systems experience
    Preferred Qualifications:

    Bachelor’s degree in Computer Science, IT, or related field (recent graduates
    encouraged to apply) Exposure to Java/JEE, Spring Boot, Kubernetes, and Docker
    Familiarity with RESTful web services, microservices, and database concepts (SQL/PLSQL,
    Oracle) Experience with tools such as Swagger, Postman, GitLab, and exposure to
    monitoring tools like Splunk or AppDynamics Skills

    Experience with Java/JEE development and exposure to Spring Boot frameworks Familiarity
    with Python or Unix scripting Understanding of SQL / PL-SQL and relational database
    concepts (Oracle preferred) Exposure to RESTful APIs, GitLab, and Postman Ability
    to read, write, speak and understand English Basic knowledge of coding principles
    Knowledge of coding language and syntax, usage of functions and object-oriented
    patterns Understanding of applicable technical systems and programming in a general
    sense Ability to follow standard practices and procedures in analyzing situations
    or data from which answers can be readily obtained and work on problems of limited
    scope Working Conditions

    Office environment



    Here, our employees don’t just have jobs, they''re building careers. That’s why
    we offer a comprehensive pay and benefits package that rewards employees for their
    contributions to our success, supporting all aspects of their well-being at every
    stage of life.


    A qualified applicant’s criminal history, if any, will be considered in a manner
    consistent with applicable laws, including local ordinances.


    Get to Know Us Charter Communications is known by our Spectrum products and services,
    including: Spectrum Internet®, TV, Mobile and Voice, Spectrum Networks, Spectrum
    Business and Spectrum Reach. When you join our team, you’ll be keeping our customers
    connected to what matters most in 41 states across the U.S. Watch this video to
    learn more.

    Grow Your Career Here We’re committed to growing a workforce that reflects the
    customers and communities we serve – providing opportunities for employment and
    advancement to all team members. Spectrum is an Equal Opportunity Employer, including
    job seekers with disabilities and veterans. Learn about Life at Spectrum. '
- job_id: META602185522792581
  job_title: Software Engineer, Product
  company_name: Meta
  status: pending
  posting_link: https://www.metacareers.com/jobs/602185522792581
  job_description: ' Meta Platforms, Inc. (Meta), formerly known as Facebook Inc.,
    builds technologies that help people connect, find communities, and grow businesses.
    When Facebook launched in 2004, it changed the way people connect. Apps and services
    like Messenger, Instagram, and WhatsApp further empowered billions around the
    world. Now, Meta is moving beyond 2D screens toward immersive experiences like
    augmented and virtual reality to help build the next evolution in social technology.
    To apply, click “Apply to Job” online on this web page. Software Engineer, Product
    Responsibilities Develop full stack web/mobile application development with a
    variety of coding languages. Create consumer products and features using internal
    programming language Hack. Work closely with our PM and design teams to define
    feature specifications and build products leveraging frameworks such as React
    & React Native. Work closely with operations and infrastructure to build and scale
    back-end services. Build report interfaces and data feeds. Establish self as an
    owner of a particular component, feature or system with expert end-to-end understanding.
    Successfully complete projects at large scope while maintaining a consistent high
    level of productivity. Minimum Qualifications Requires a Bachelor''s degree in
    Computer Science, Computer Engineering or a related field and 6 months of experience
    in the job offered or in a computer-related occupation. Experience must include
    6 months of experience in the following: 1. Coding in at least one of the following
    industry-standard languages: C, C++, Java, or C# 2. Experience in software development
    tools: Code editors (VIM or Emacs), and version control systems (Subversion, GIT,
    or Perforce) 3. Experience in Linux, Unix OS as evidenced by file manipulation,
    advanced commands, and shell scripting 4. Experience with scripting languages
    such as Python, Javascript or Hack 5. Experience building large-scale applications
    or similar experience 6. Experience as an owner of a particular component, feature
    or system 7. Experience completing projects at large scope 8. Experience building
    and shipping high quality work and achieving high reliability 9. Track record
    of setting technical direction for a team, driving consensus and successful cross-functional
    partnerships 10. Experience improving quality through thoughtful code reviews,
    appropriate testing, proper rollout, monitoring, and proactive changes 11. Experience
    with relational databases and SQL 12. Experience implementing web interfaces using
    at least one of the following: JavaScript, HTML, or CSS 13. Distributed systems.
    For those who live in or expect to work from California if hired for this position,
    please click here for additional information. About Meta Meta builds technologies
    that help people connect, find communities, and grow businesses. When Facebook
    launched in 2004, it changed the way people connect. Apps like Messenger, Instagram
    and WhatsApp further empowered billions around the world. Now, Meta is moving
    beyond 2D screens toward immersive experiences like augmented and virtual reality
    to help build the next evolution in social technology. People who choose to build
    their careers by building with us at Meta help shape a future that will take us
    beyond what digital connection makes possible today—beyond the constraints of
    screens, the limits of distance, and even the rules of physics.

    $217,260/year to $240,240/year + bonus + equity + benefits

    Individual compensation is determined by skills, qualifications, experience, and
    location. Compensation details listed in this posting reflect the base hourly
    rate, monthly rate, or annual salary only, and do not include bonus, equity or
    sales incentives, if applicable. In addition to base compensation, Meta offers
    benefits. Learn more about benefits at Meta.

    Equal Employment Opportunity Meta is proud to be an Equal Employment Opportunity
    employer. We do not discriminate based upon race, religion, color, national origin,
    sex (including pregnancy, childbirth, reproductive health decisions, or related
    medical conditions), sexual orientation, gender identity, gender expression, age,
    status as a protected veteran, status as an individual with a disability, genetic
    information, political views or activity, or other applicable legally protected
    characteristics. You may view our Equal Employment Opportunity notice here. Meta
    is committed to providing reasonable accommodations for qualified individuals
    with disabilities and disabled veterans in our job application procedures. If
    you need assistance or an accommodation due to a disability, fill out the Accommodations
    request form. '
