- job_id: AMZ26535.1
  job_title: Software Dev Engineer II
  company_name: Amazon Web Services
  status: processed
  job_description: 'Description Employer: Amazon Web Services, Inc. Position: Software
    Dev Engineer II Location: Arlington, VA

    Multiple Positions Available:

    Design, develop, implement, test, and document embedded or distributed software
    applications, tools, systems and services. Translate functional requirements into
    robust, efficient, supportable solutions that work well within the overall system
    architecture. Participate in the full development cycle, end-to-end, from design,
    implementation, and testing to documentation, delivery and maintenance. Produce
    comprehensive, usable software documentation. Evaluate and make decisions around
    the use of new or existing software products and tools. Mentor junior development
    engineers.


    Basic Qualifications Bachelor''s degree or foreign equivalent degree in Computer
    Science, Engineering, Mathematics, or a related field and one year of experience
    in the job offered or a related occupation. Must have one year of experience in
    the following skill(s): (1) designing and developing large-scale, multi-tiered,
    multi-threaded, embedded or distributed software applications, tools, systems,
    and services using: (i.) C#, C++, Java, or Perl; and (ii.) Object Oriented Design.


    Preferred Qualifications All applicants must meet all the above listed requirements.

    Amazon is an equal opportunity employer and does not discriminate on the basis
    of protected veteran status, disability, or other legally protected status.

    Our inclusive culture empowers Amazonians to deliver the best results for our
    customers. If you have a disability and need a workplace accommodation or adjustment
    during the application and hiring process, including support for the interview
    or onboarding process, please visit https://amazon.jobs/content/en/how-we-hire/accommodations
    for more information. If the country/region you’re applying in isn’t listed, please
    contact your Recruiting Partner.

    '
- job_id: nokia24918
  job_title: AI R&D Engineer Co-op
  company_name: Nokia
  status: processed
  job_description: 'About Us:

    United States (On-site) Position: AI R&D Engineer Co-op Number of Position(s):
    1 Duration: 4 Months Date: January 12–May 22, 2026 Location:  Onsite


    Education Recommendations:

    Currently a candidate for a Master’s or PhD degree in Computer Science or Engineering,
    Mathematics, or a related field with an accredited school in the US.

    HOW YOU WILL CONTRIBUTE AND WHAT YOU WILL LEARN As part of our team, you will:

    Design, develop, and deploy advanced AI/ML models and algorithms to analyze and
    interpret complex data. Design and implement machine learning models to improve
    a wide range of applications, including search, forecasting, text mining, and
    more. Develop and implement agentic-based systems for a wide range of applications,
    including anomaly detection, root-cause analysis, and more. Optimize existing
    machine learning models and pipelines for performance, scalability, and resource
    efficiency. Qualifications Experience with: Machine learning, optimization algorithms,
    and deep-learning techniques. Machine learning frameworks (e.g., TensorFlow, PyTorch).
    Search engines and vector databases, along with their underlying algorithms. Big
    data frameworks and technologies such as Spark, Kafka, and Cassandra. Excellent
    communication skills and is a team player. About Us Come create the technology
    that helps the world act together

    Nokia is committed to innovation and technology leadership across mobile, fixed
    and cloud networks. Your career here will have a positive impact on people’s lives
    and will help us build the capabilities needed for a more productive, sustainable,
    and inclusive world. We challenge ourselves to create an inclusive way of working
    where we are open to new ideas, empowered to take risks and fearless to bring
    our authentic selves to work

    What we offer

    Nokia offers continuous learning opportunities, well-being programs to support
    you mentally and physically, opportunities to join and get supported by employee
    resource groups, mentoring programs and highly diverse teams with an inclusive
    culture where people thrive and are empowered.

    Nokia is committed to inclusion and is an equal opportunity employer

    Nokia has received the following recognitions for its commitment to inclusion
    & equality:

    One of the World’s Most Ethical Companies by Ethisphere Gender-Equality Index
    by Bloomberg Workplace Pride Global Benchmark At Nokia, we act inclusively and
    respect the uniqueness of people. Nokia’s employment decisions are made regardless
    of race, color, national or ethnic origin, religion, gender, sexual orientation,
    gender identity or expression, age, marital status, disability, protected veteran
    status or other characteristics protected by law. We are committed to a culture
    of inclusion built upon our core value of respect. Join us and be part of a company
    where you will feel included and empowered to succeed.

    Additional Information

    US/Canada Nokia Offers a comprehensive benefits package that includes but is not
    limited to: Corporate Retirement Savings Plan Health and dental benefits Short-term
    disability, and long-term disability Life insurance, and AD&D – Company paid 2x
    base pay Optional or Supplemental life and AD&D insurance (Employee/Spouse/Child)
    Paid time off for holidays and Vacation Employee Stock Purchase Plan Tuition Assistance
    Plan Adoption assistance Employee Assistance Program/Work Life Resource Program
    The above benefits exclude students. Disclaimer for US/Canada

    Nokia Maintains broad annual base salary ranges for its roles in order to account
    for variations in knowledge, skills, experience and market conditions, and with
    consideration to internal peer equity.(Check the salary ranges in the job info
    section for this role)

    All North America job posts will post for a minimum of 7 calendar days and up
    to 180 days or until candidate/s identified. About the Team As Nokia''s growth
    engine, we create value for communication service providers and enterprise customers
    by leading the transition to cloud-native software and as-a-service delivery models.
    Our inclusive team of dreamers, doers and disruptors push the limits from impossible
    to possible.

    '
- job_id: add58865-8b9f-4cf7-9720-2908ba5f4d80
  job_title: Software Engineer, Infrastructure, Early Career
  company_name: Notion
  status: processed
  job_description: 'About Us:

    Notion helps you build beautiful tools for your life’s work. In today''s world
    of endless apps and tabs, Notion provides one place for teams to get everything
    done, seamlessly connecting docs, notes, projects, calendar, and email—with AI
    built in to find answers and automate work. Millions of users, from individuals
    to large organizations like Toyota, Figma, and OpenAI, love Notion for its flexibility
    and choose it because it helps them save time and money.


    In-person collaboration is essential to Notion''s culture. We require all team
    members to work from our offices on Mondays and Thursdays, our designated Anchor
    Days. Certain teams or positions may require additional in-office workdays.


    About the Role:

    As a Software Engineer, Infrastructure (Early Career), you’ll help build and operate
    the platform that powers Notion for millions of users. You’ll work on services,
    storage, data, networking, observability, CI/CD, and developer experience to make
    our systems reliable, scalable, and efficient. You’ll collaborate with senior
    engineers to design and implement high‑leverage infrastructure that enables product
    teams to ship quickly and safely.


    What You''ll Achieve:

    Ship improvements to core infrastructure that increase reliability, performance,
    scalability, and cost efficiency.


    Contribute to backend systems that meet the needs of over 100 million global users,
    large enterprise customers, and our rapidly growing business.


    Build and maintain observability, alerting, and incident tooling to reduce MTTR
    and improve on‑call experience.


    Develop the skills and confidence to debug live production systems with minimal
    disruption. You will participate in an on-call rotation, responding to incidents
    to uphold service reliability and quickly restore normal operations.


    Automate operations with tooling and infrastructure‑as‑code to make our systems
    easy to run and evolve.


    Partner with our security teams to implement best practices for hardening, secrets,
    access, and compliance.


    Areas You Might Work On:

    Storage and databases: schema design, migrations, performance tuning, caching.


    Compute and orchestration: service frameworks, containerization, CI/CD, rollout
    safety.


    Observability: metrics, tracing, logging, SLOs, dashboards.


    Networking and edge: APIs, rate limiting, load balancing, traffic shaping, CDN.


    Platform foundations: developer tooling, local dev ergonomics, SDKs, testing infra.


    Reliability engineering: capacity planning, failover, disaster recovery, chaos
    testing.


    Skills You''ll Need to Bring:

    BS or MS in Computer Science or related field, or equivalent practical experience.


    Proficiency in at least one general‑purpose programming language such as Typescript,
    Python, Rust, Go, Java, Python, or C++.


    Solid CS fundamentals in data structures, algorithms, systems, and networking.


    Experience from internships or projects building backend services , infrastructure,
    or full stack products.


    Strong communication skills and a collaborative, product‑minded approach.


    Nice to Haves:

    Familiarity with distributed systems, databases, and concurrency.


    Familiarity with Linux, cloud platforms (e.g., AWS or GCP), and containers.


    Exposure to Infrastructure‑as‑Code (e.g., Terraform), container orchestration,
    or service meshes.


    Hands‑on with observability stacks (e.g., Prometheus, OpenTelemetry, Grafana).


    We hire talented and passionate people from a variety of backgrounds because we
    want our global employee base to represent the wide diversity of our customers.
    If you’re excited about a role but your past experience doesn’t align perfectly
    with every bullet point listed in the job description, we still encourage you
    to apply. If you’re a builder at heart, share our company values, and enthusiastic
    about making software toolmaking ubiquitous, we want to hear from you.


    Notion is proud to be an equal opportunity employer. We do not discriminate in
    hiring or any employment decision based on race, color, religion, national origin,
    age, sex (including pregnancy, childbirth, or related medical conditions), marital
    status, ancestry, physical or mental disability, genetic information, veteran
    status, gender identity or expression, sexual orientation, or other applicable
    legally protected characteristic. Notion considers qualified applicants with criminal
    histories, consistent with applicable federal, state and local law. Notion is
    also committed to providing reasonable accommodations for qualified individuals
    with disabilities and disabled veterans in our job application procedures. If
    you need assistance or an accommodation due to a disability, please let your recruiter
    know.


    Notion is committed to providing highly competitive cash compensation, equity,
    and benefits. The compensation offered for this role will be based on multiple
    factors such as location, the role’s scope and complexity, and the candidate’s
    experience and expertise, and may vary from the range provided below. For roles
    based in San Francisco or New York City, the estimated base salary range for this
    role is $126k - $155k per year.



    By clicking “Submit Application”, I understand and agree that Notion and its affiliates
    and subsidiaries will collect and process my information in accordance with Notion’s
    Global Recruiting Privacy Policy.


    #LI-Onsite

    '
