- job_id: OPJOPEUS49046
  job_title: Associate Software Engineer
  company_name: OpenText
  location: India
  status: processed
  posting_link: https://careers.opentext.com/us/en/job/OPJOPEUS49046EXTERNALENUS/Associate-Software-Engineer
  job_description: ' Description OPENTEXT - THE INFORMATION COMPANY

    OpenText is a global leader in information management, where innovation, creativity,
    and collaboration are the key components of our corporate culture. As a member
    of our team, you will have the opportunity to partner with the most highly regarded
    companies in the world, tackle complex issues, and contribute to projects that
    shape the future of digital transformation.



    AI-First. Future-Driven. Human-Centered.

    At OpenText, AI is at the heart of everything we do—powering innovation, transforming
    work, and empowering digital knowledge workers. We''re hiring talent that AI can''t
    replace to help us shape the future of information management. Join us.




    YOUR IMPACT :

    We are looking for a passionate and driven Associate Software Engineer to join
    our dynamic Digital Solutions team. In this role, you will be involved in designing,
    developing, and deploying scalable full-stack applications using modern technologies
    and frameworks. You will collaborate closely with senior engineers, architects,
    and product managers to build solutions that make a meaningful impact.

    This is a fantastic opportunity for early-career professionals who are eager to
    grow, learn, and contribute to complex and impactful software development projects
    in a fast-paced, collaborative environment.


    WHAT THE ROLE OFFERS :

    Deliver high-quality, production-ready code under the guidance of senior team
    members. Participate in design, development, testing, and deployment of software
    applications. Execute assigned tasks effectively and contribute to solving real
    customer problems. Work closely with team members to understand business requirements
    and customer pain points. Translate design ideas and business logic into clean,
    maintainable, and well-documented code. Adhere to coding standards, participate
    in code reviews, and follow software engineering best practices. Engage in Agile
    ceremonies and contribute to iterative development cycles. Take ownership of assigned
    work, follow through on commitments, and meet delivery timelines. Continuously
    learn and stay up to date with new technologies, frameworks, and industry trends.

    WHAT YOU NEED TO SUCCEED :

    1–3 years of hands-on experience in Java / Java EE and backend development. Proficiency
    with front-end technologies: HTML, CSS, JavaScript, and frameworks like Angular
    (12+) or Ext JS. Solid understanding of RESTful API design and development. Experience
    with frameworks such as Spring, Spring Boot, Hibernate, iBATIS, and JPA. Familiarity
    with application servers (e.g., Tomcat, WebLogic Server). Hands-on experience
    using IDEs like Eclipse, IntelliJ, or JBuilder. Version control expertise with
    tools such as Git or Mercurial. Working knowledge of Red Hat Linux, Shell scripting,
    and build/integration tools like Maven. Exposure to Ansible, Docker containers,
    and CI/CD concepts is a plus. Understanding of design patterns, database modeling,
    and service-oriented architectures. Awareness of Agile methodologies (Scrum) and
    ability to thrive in a collaborative, cross-functional team setup.


    Required Qualifications


    BE/BS/BTech or ME/MS/MTech in Computer Science, Computer Engineering, or a closely
    related technical field. Strong analytical and problem-solving skills with a proactive
    mindset. Excellent communication skills—both verbal and written. Ability to work
    independently as well as in a fast-paced team-oriented environment. Eagerness
    to learn, take feedback constructively, and grow within the organization.






    OpenText''s efforts to build an inclusive work environment go beyond simply complying
    with applicable laws. Our Employment Equity and Diversity Policy provides direction
    on maintaining a working environment that is inclusive of everyone, regardless
    of culture, national origin, race, color, gender, gender identification, sexual
    orientation, family status, age, veteran status, disability, religion, or other
    basis protected by applicable laws.

    If you need assistance and/or a reasonable accommodation due to a disability during
    the application or recruiting process, please contact us at hr@opentext.com. Our
    proactive approach fosters collaboration, innovation, and personal growth, enriching
    OpenText''s vibrant workplace. '
- job_id: JR263074
  job_title: Software Engineering AMTS
  company_name: Salesforce
  location: India
  status: processed
  posting_link: https://salesforce.wd12.myworkdayjobs.com/External_Career_Site/job/India---Hyderabad/Software-Engineering-AMTS_JR263074
  job_description: '

    About Futureforce University Recruiting

    Our Futureforce University Recruiting program is dedicated to attracting, retaining
    and cultivating talent. Our interns and new graduates work on real projects that
    affect how our business runs, giving them the opportunity to make a tangible impact
    on the future of our company. With offices all over the world, our recruits have
    the chance to collaborate and connect with fellow employees on a global scale.
    We offer job shadowing, mentorship programs, talent development courses, and much
    more.

    Job Category

    Software Engineering Job Details

    About Salesforce

    Salesforce is the #1 AI CRM, where humans with agents drive customer success together.
    Here, ambition meets action. Tech meets trust. And innovation isn’t a buzzword
    — it’s a way of life. The world of work as we know it is changing and we''re looking
    for Trailblazers who are passionate about bettering business and the world through
    AI, driving innovation, and keeping Salesforce''s core values at the heart of
    it all.

    Ready to level-up your career at the company leading workforce transformation
    in the agentic era? You’re in the right place! Agentforce is the future of AI,
    and you are the future of Salesforce.

    Job Description

    About Salesforce

    We’re Salesforce, the Customer Company, inspiring the future of business with
    AI+ Data +CRM. Leading with our core values, we help companies across every industry
    blaze new trails and connect with customers in a whole new way. And, we empower
    you to be a Trailblazer, too — driving your performance and career growth, charting
    new paths, and improving the state of the world. If you believe in business as
    the greatest platform for change and in companies doing well and doing good –
    you’ve come to the right place.

    Want your line of code to have a significant and measurable positive impact on
    users, the company’s bottom line, and industry? Join Salesforce and define the
    future of cloud computing. We deliver a scalable, high performance cloud computing
    platform that delights our customers, and is used by millions of people around
    the world each day for their business. You will be working with a group of world-class
    engineers to build breakthrough features that our customers will love, adopt and
    use while keeping our trusted platform stable and scalable. The software engineer
    role at Salesforce encompasses architecture, design, implementation, and testing
    to ensure we build products right and release them with high quality.


    From Marketing Cloud to Service Cloud, Platform to IoT, Einstein Platform, Security
    and everything in between we have many opportunities available across various
    applications and platforms. Apply now and we look forward to reaching out to you
    with opportunities that fit your background and interests!


    Key Responsibilities:

    Architect, design, implement, test and deliver highly scalable products

    Master our development process, culture and code base, then improve it

    Work closely with a team of engineers, product managers, user experience experts
    and performance engineers to build new features our customers will love, adopt
    and use while keeping our trusted platform stable and scalable

    Develop test strategies, design automation frameworks, write unit/functional tests
    to drive up code coverage and automation metrics

    Analyze, design and develop test cases and implement automated test suites

    Desired Skills:

    Strong analytical and problem-solving skills

    Team-player with the ability to work effectively and efficiently with others

    Be a self-starter and possess strong sense of self-motivation

    Experience using telemetry and metrics to drive operational excellence

    Eligibility criteria:

    B.E/ B.Tech graduating in 2025 in Computer Science, Electrical, Electronics, or
    equivalent fields with specialization in computer science. ​

    7 CGPA and above with no backlogs.

    About Futureforce University Recruiting

    Our Futureforce University Recruiting program is dedicated to attracting, retaining
    and cultivating talent. Our interns and new graduates work on real projects that
    affect how our business runs, giving them the opportunity to make a tangible impact
    on the future of our company. With offices all over the world, our recruits have
    the chance to collaborate and connect with fellow employees on a global scale.
    We offer job shadowing, mentorship programs, talent development courses, and much
    more.

    Accommodations

    If you require assistance due to a disability applying for open positions please
    submit a request via this Accommodations Request Form.

    Posting Statement

    At Salesforce we believe that the business of business is to improve the state
    of our world. Each of us has a responsibility to drive Equality in our communities
    and workplaces. We are committed to creating a workforce that reflects society
    through inclusive programs and initiatives such as equal pay, employee resource
    groups, inclusive benefits, and more. Learn more about Equality at www.equality.com
    and explore our company benefits at www.salesforcebenefits.com.

    Salesforce is an Equal Employment Opportunity and Affirmative Action Employer.
    Qualified applicants will receive consideration for employment without regard
    to race, color, religion, sex, sexual orientation, gender perception or identity,
    national origin, age, marital status, protected veteran status, or disability
    status. Salesforce does not accept unsolicited headhunter and agency resumes.
    Salesforce will not pay any third-party agency or company that does not have a
    signed agreement with Salesforce. Salesforce welcomes all.

    Unleash Your Potential

    When you join Salesforce, you’ll be limitless in all areas of your life. Our benefits
    and resources support you to find balance and be your best, and our AI agents
    accelerate your impact so you can do your best. Together, we’ll bring the power
    of Agentforce to organizations of all sizes and deliver amazing experiences that
    customers love. Apply today to not only shape the future — but to redefine what’s
    possible — for yourself, for AI, and the world.

    Accommodations

    If you require assistance due to a disability applying for open positions please
    submit a request via this Accommodations Request Form.

    Posting Statement

    Salesforce is an equal opportunity employer and maintains a policy of non-discrimination
    with all employees and applicants for employment. What does that mean exactly?
    It means that at Salesforce, we believe in equality for all. And we believe we
    can lead the path to equality in part by creating a workplace that’s inclusive,
    and free from discrimination. Know your rights: workplace discrimination is illegal.
    Any employee or potential employee will be assessed on the basis of merit, competence
    and qualifications – without regard to race, religion, color, national origin,
    sex, sexual orientation, gender expression or identity, transgender status, age,
    disability, veteran or marital status, political viewpoint, or other classifications
    protected by law. This policy applies to current and prospective employees, no
    matter where they are in their Salesforce employment journey. It also applies
    to recruiting, hiring, job assignment, compensation, promotion, benefits, training,
    assessment of job performance, discipline, termination, and everything in between.
    Recruiting, hiring, and promotion decisions at Salesforce are fair and based on
    merit. The same goes for compensation, benefits, promotions, transfers, reduction
    in workforce, recall, training, and education.


    '
